# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
players = Player.create([{
  id: '1',
  location_id: '1',
  level: '1',
  sex: 'M',
  dob: '1967-06-26',
  occupation: 'software guy',
  energy: '95',
  food: '90',
  water: '85',
  bio: '80',
  money: '75',
  confidence: '70',
  attractiveness: '65',
  charisma: '60',
  status: '55',
  intelligence: '50',
  luck: '45'
}]);

Locations = Location.create([{
  id: '1',
  lat: 45.516858,
  lng: -122.628558
}]);

Places = Place.create([{
  id: '1',
  location_id: '1',
  player_id: '1',
  name: 'the Launching Pad'
}]);

PlaceTypes = PlaceType.create([
  { name:  'accounting', label: 'Accounting' },
  { name:  'airport', label: 'Airport' },
  { name:  'amusement_park', label: 'Amusement Park' },
  { name:  'aquarium', label: 'aquarium' },
  { name:  'art_gallery', label: 'Art Gallery' },
  { name:  'atm', label: 'ATM' },
  { name:  'bakery', label: 'Bakery' },
  { name:  'bank', label: 'Bank' },
  { name:  'bar', label: 'Bar' },
  { name:  'beauty_salon', label: 'Beauty Salon' },
  { name:  'bicycle_store', label: 'Bicycle Store' },
  { name:  'book_store', label: 'Book Store' },
  { name:  'bowling_alley', label: 'Bowling Alley' },
  { name:  'bus_station', label: 'Bus Station' },
  { name:  'cafe', label: 'Cafe' },
  { name:  'campground', label: 'Campground' },
  { name:  'car_dealer', label: 'Car Dealer' },
  { name:  'car_rental', label: 'Car Rental' },
  { name:  'car_repair', label: 'Car Repair' },
  { name:  'car_wash', label: 'Car Wash' },
  { name:  'casino', label: 'Casino' },
  { name:  'cemetery', label: 'Cemetery' },
  { name:  'church', label: 'Church' },
  { name:  'city_hall', label: 'City Hall' },
  { name:  'clothing_store', label: 'Clothing Store' },
  { name:  'convenience_store', label: 'Convenience Store' },
  { name:  'courthouse', label: 'Courthouse' },
  { name:  'dentist', label: 'Dentist' },
  { name:  'department_store', label: 'Department Store' },
  { name:  'doctor', label: 'Doctor' },
  { name:  'electrician', label: 'Electrician' },
  { name:  'electronics_store', label: 'Electronics Store' },
  { name:  'embassy', label: 'Embassy' },
  { name:  'establishment', label: 'Establishment' },
  { name:  'finance', label: 'Finance' },
  { name:  'fire_station', label: 'Fire Station' },
  { name:  'florist', label: 'Florist' },
  { name:  'food', label: 'Food' },
  { name:  'funeral_home', label: 'Funeral Home' },
  { name:  'furniture_store', label: 'Furniture Store' },
  { name:  'gas_station', label: 'Gas Station' },
  { name:  'general_contractor', label: 'General Contractor' },
  { name:  'geocode', label: 'Geocode' },
  { name:  'grocery_or_supermarket', label: 'Grocery or Supermarket' },
  { name:  'gym', label: 'Gym' },
  { name:  'hair_care', label: 'Hair Care' },
  { name:  'hardware_store', label: 'Hardware Store' },
  { name:  'health', label: 'Health' },
  { name:  'hindu_temple', label: 'Hindu Temple' },
  { name:  'home_goods_store', label: 'Home Goods Store' },
  { name:  'hospital', label: 'Hospital' },
  { name:  'insurance_agency', label: 'Insurance Agency' },
  { name:  'jewelry_store', label: 'Jewelry Store' },
  { name:  'laundry', label: 'Laundry' },
  { name:  'lawyer', label: 'Lawyer' },
  { name:  'library', label: 'Library' },
  { name:  'liquor_store', label: 'Liquor Store' },
  { name:  'local_government_office', label: 'Local Government Office' },
  { name:  'locksmith', label: 'Locksmith' },
  { name:  'lodging', label: 'Lodging' },
  { name:  'meal_delivery', label: 'Meal Delivery' },
  { name:  'meal_takeaway', label: 'Meal Takeaway' },
  { name:  'mosque', label: 'Mosque' },
  { name:  'movie_rental', label: 'Movie Rental' },
  { name:  'movie_theater', label: 'Movie Theater' },
  { name:  'moving_company', label: 'Moving Company' },
  { name:  'museum', label: 'Museum' },
  { name:  'night_club', label: 'Night Club' },
  { name:  'painter', label: 'Painter' },
  { name:  'park', label: 'Park' },
  { name:  'parking', label: 'Parking' },
  { name:  'pet_store', label: 'Pet Store' },
  { name:  'pharmacy', label: 'Pharmacy' },
  { name:  'physiotherapist', label: 'Physiotherapist' },
  { name:  'place_of_worship', label: 'Place of Worship' },
  { name:  'plumber', label: 'Plumber' },
  { name:  'police', label: 'Police' },
  { name:  'post_office', label: 'Post Office' },
  { name:  'real_estate_agency', label: 'Real Estate Agency' },
  { name:  'restaurant', label: 'Restaurant' },
  { name:  'roofing_contractor', label: 'Roofing Contractor' },
  { name:  'rv_park', label: 'RV Park' },
  { name:  'school', label: 'School' },
  { name:  'shoe_store', label: 'Shoe Store' },
  { name:  'shopping_mall', label: 'Shopping Mall' },
  { name:  'spa', label: 'Spa' },
  { name:  'stadium', label: 'Stadium' },
  { name:  'storage', label: 'Storage' },
  { name:  'store', label: 'Store' },
  { name:  'subway_station', label: 'Subway Station' },
  { name:  'synagogue', label: 'Synagogue' },
  { name:  'taxi_stand', label: 'Taxi Stand' },
  { name:  'train_station', label: 'Train Station' },
  { name:  'travel_agency', label: 'Travel Agency' },
  { name:  'university', label: 'University' },
  { name:  'veterinary_care', label: 'Veterinary Care' },
  { name:  'zoo', label: 'Zoo' }
]);
